version: "2.1"
services:
  rabbitmq:
    restart: unless-stoppedalways
    build: ../../rabbitmq
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
      - "rabbitmq-data:/etc/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [backing-services]
  vault:
    restart: unless-stopped
    image: vault:0.8.1
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: spring-cloud-examples-vault-token
      VAULT_LOCAL_CONFIG: '
        {
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "default_lease_ttl": "768h",
          "max_lease_ttl": "768h",
          "disable_mlock": true,
          "cluster_name": "vault-cluster"
        }
      '
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - "vault-data:/var/logs"
      - "vault-data:/etc/file"
      - "vault-data:/vault"
    networks: [backing-services]
volumes:
  rabbitmq-data: {}
  vault-data: {}
networks:
  backing-services:
    driver: bridge
