group: trusty_lts
service:
- docker
language: java
#jdk:
#- openjdk8
#- oraclejdk8
install: true
before_install:
- sudo apt update -Y || true
# install docker-compose
- sudo apt install -y --no-install-recommends docker-ce python-pip curl jq libxml2-utils libappindicator1 fonts-liberation
- sudo pip install docker-compose httpie
# frontend tests
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
# kill on ports
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 3000 8000 8080 80 27017 5672 5432
script:
- bash gradlew clean build asciidoctor
- export ROOT=$PWD
- >
  for path in \
    07-spring-cloud-stream \
    05-spring-cloud-task \
    04-config-server-overrides \
    04-native-search-locations \
    04-config-server-native \
    03-config-server-vault \
    02-config-server-zipkin-server \
    01-config-server-encryption-decryption \
    01-spring-cloud-config-server \
    0-spring-cloud-template ;
  do
    export TARGET="$ROOT/$path"
    cd $TARGET
    bash gradlew clean assemble
    bash gradlew composeUp
    bash gradlew composeDown
  done;
cache:
  directories:
  - $HOME/.m2/
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
