version: "2.1"
services:
  rabbitmq:
    restart: unless-stopped
    build: ../../rabbitmq
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
      - "rabbitmq-data:/etc/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [backing-services]
  spring-cloud-simple-task:
    #restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    build: ../../spring-cloud-simple-task
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    volumes: ["spring-cloud-simple-task-data:/opt/app"]
    #ports: ["8080:8080"]
    networks: [backing-services]
volumes:
  rabbitmq-data: {}
  spring-cloud-simple-task-data: {}
networks:
  backing-services:
    driver: bridge
