---
spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/daggerok/spring-cloud-examples
          search-paths: 01-spring-cloud-config-server/config-server/spring-config-repository
          force-pull: true
app:
  foo: bar
---
spring:
  profiles:
    active: cloud
app:
  bar: foo
