version: "2.1"
services:
  consul:
    restart: unless-stopped
    image: consul:0.9.2
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_HTTP_ADDR: 0.0.0.0
      CONSUL_ALLOW_PRIVILEGED_PORTS:
      CONSUL_LOCAL_CONFIG: '
        {
          "leave_on_terminate": true,
          "skip_leave_on_interrupt": true,
          "disable_update_check": true
        }
      '
      # curl http://localhost:8500/v1/health/service/consul?pretty
    ports:
      - "8500:8500"
      - "8600:53/udp"
    volumes:
      - "consul-data:/consul/data"
      - "consul-data:/consul/config"
#    networks: [backing-services]
  vault:
    restart: unless-stopped
    depends_on: [consul]
    image: vault:0.8.1
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: spring-cloud-examples-vault-token
      VAULT_LOCAL_CONFIG: '
        {
          "storage": {
            "consul": {
              "address": "consul:8500",
              "path": "vault"
            }
          },
          "default_lease_ttl": "768h",
          "max_lease_ttl": "768h",
          "disable_mlock": true,
          "cluster_name": "vault-cluster"
        }
      '
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - "vault-data:/var/logs"
      - "vault-data:/etc/file"
      - "vault-data:/vault/config"
#    networks: [backing-services]
volumes:
  consul-data: {}
  vault-data: {}
networks:
  backing-services:
    driver: bridge
