version: "2.1"
services:
  vault:
    restart: unless-stopped
    build: ../../vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: spring-cloud-examples-vault-token
      VAULT_LOCAL_CONFIG: '
        {
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },
          "default_lease_ttl": "768h",
          "max_lease_ttl": "768h",
          "disable_mlock": true,
          "cluster_name": "vault-cluster"
        }
      '
    ports: ["8200:8200"]
    volumes:
      - "vault-data:/vault/logs"
      - "vault-data:/vault/file"
    networks: [backing-services]
  rabbitmq:
    restart: unless-stopped
    build: ../../rabbitmq
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
      - "rabbitmq-data:/etc/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    networks: [backing-services]
  config-server:
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      vault:
        condition: service_healthy
    build: ../../config-server
    environment:
      SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST: vault
      SPRING_RABBITMQ_HOST: rabbitmq
    volumes: ["config-server-data:/opt/app"]
    ports: ["8888:8888"]
    networks: [backing-services]
volumes:
  vault-data: {}
  rabbitmq-data: {}
  config-server-data: {}
networks:
  backing-services:
    driver: bridge
